### ISSUE TITLE
Créer un mode vacances

### ISSUE THREAD

**Issue by JedXDs** [Virtual-Royaume/Royaume-Discord-Bot#106]
Créer une commande vacances pour que lorsque des personnes partent en vacances, ça n'affecte pas son rôle

**Comment by Steellgold** [comment]
J'adore l'idée !

**Comment by Steellgold** [comment]
J'adore l'idée !

Par contre il y a des points où cette commande peut être mal utilisé

- Il faudrait qu'il ne puisse pas l'utiliser 5 (à voir) jours avant le 1er du mois
Car sinon ce sera trop facile de rester dans son rôle
- Quelle puisse être active seulement en début de mois
Car je pense c'est mieux, si il l'utilise au milieu du mois juste car il a la flemme d'être actif bon..

C'est des simples idées pour contrer certains points @JedXDs

Qu'en pensez vous @Virtual-Royaume/royaume-dev ?

**Comment by JedXDs** [comment]
Ca se base sur la confiance aussi. Ça sert à rien je trouve de mettre des choses pour éviter le changement de rôle. Bien sûr que si ça fait 3 mois qu'il est en vacances c'est moins logique.

**Comment by Steellgold** [comment]
Ah ouais je vois ok, j'avais pas pensé dans se sens aussi

**Comment by Verre2OuiSki** [comment]
**Avec réflexion, je trouve que cette commande est contraire a l'idée initiale du système d'activité :** _« Acquisition d'un rôle selon activité dans le mois »_

Pourquoi vouloir garder un rang, alors que l'on apporte aucun contenu a la communauté ? Certes il est inactif contre son gré, mais cela n'empêche pas qu'il n'a rien apporté pendant un certain laps de temps.
Voici pourquoi ce système de vacance est complètement inutile :
> _Ici, nous allons dire que les périodes de vacances durent 1 mois, et commencent au début du mois_
- Si tu es R1 et complètement inactif _(vraiment a 100%),_ tu n'auras aucun problème pour remonter a ton rôle. Si tu es R1, c'est que tu as été l'un des plus actif du serveur 4 fois minimum, et que tu as maintenu un import en contenu chaque mois. Dans le pire des cas, tu resteras R2, et si c'est les cas, c'est que tu n'es plus aussi actif qu'avant, donc représentatif de ton activité.
- Pour les gens ayant un rôles stagnant, c'est qu'ils ne sont pas assez actif pour monter, et ils ne monteront pas. Ils ne peuvent que descendre ou rester sur le seuil de la descente de rang. Donc pourquoi vouloir leur faire garder leur statu ? Ces gens gardes leur rang uniquement car ils ont légèrement plus de points que les moins actif et inactif du serveur.

De plus, d'un point de vu technique, je ne vois pas comment tu veux mettre ca en place. La durée de vacance dépend énormément. D'un simple jour, a deux mois voir plus...
Comment faire pour geler le rôle pour ne pas avoir de classements complètements aberrants ?
Tu veux geler le rôle a partir du moment ou il fait la commande ?
Il y a t-il un temps minimal a respecter pour être éligible _(si je ne suis pas la qu'un jour mon rang est-il figé ?)_ ?
Il y a t-il des conditions pour que ce gèle soit actif _(ie: ne pas poster de message pendant notre période de pause)_ ?
Beaucoup de question a se poser, pour quelque chose, qui a mes yeux, est inutile.

Pour faire en bref, je trouve cette idée contraire au système d'activité et non pertinente.

**Comment by Steellgold** [comment]
Ok

**Comment by Bluzzi** [comment]
Hello, je rejoins l'avis de @Verre2OuiSki pour cette fonctionnalité.

### Contexte
**Au delà de 1 mois :** Des vacances ? Des vraies vacances ça dur rarement plus d'un mois, au-delà c'est juste que le membre n'a plus besoin de nous pour X raison pendant bien plus longtemps et qu'il veut revenir comme une fleur 6 mois plus tard avec le même rôle d'activité.

**En dessous de 1 mois :** Des vacances de 1 mois complet c'est rare, un membre actif à son rôle n'aura aucun problème à garder son rôle avec uniquement 3-4 jours de disponibilité dans un mois, une seule discussion, un seul débat suffit, actuellement il suffit de 5 à 10 messages dans le mois pour garder son rôle.

### Mentalité 
Si la personne est vraiment absente pendant 1 mois dû à des vacances, ça ne fait qu'un mois à rattraper, si elle porte vraiment de l'importance au Discord, ça ne sera pas difficile de regagner le temps perdu. 

N'oubliez pas, notre objectif est de pousser les gens à être actif, pas le contraire, si on commence à créer des solutions pour être inactif sans pénalité, c'est fini.

Notre Discord c'est un endroit de passionné et de divertissement. Les vacances c'est fait pour vivre comme un passionné et se divertir. Quelqu'un qui n'est la que pour le côté pro et que pour obtenir de l'aide, c'est pas une bonne personne pour le Discord.

### Système 
Si la personne est en mode vacance, comment ça se passe si elle envoie des messages quand même ? Il est R1 et il veut juste rester à son rôle et pouvoir envoyer des petits messages dès qu'il se souvient de notre existence ?

Des problemes sur le moment de l'activitation ont deja était éxprimé par @Verre2OuiSki et @Steellgold, ça prouve que ce système est difficile à mettre en place. Vu que les périodes de vacance sont dans 90% des cas inférieur à 1 mois et que notre système d'activité est basé sur des périodes de 1 mois, comment ça se passe ?

### Conclusion 
Avant de vouloir mettre en place des systèmes complexes pour les pseudo-actifs, qui poussent à la possibilité d'être inactif. Concentrez-vous sur des fonctionnalités pour les personnes actives, pour pousser les gens à apprécier notre Discord, à être actif dessus et à le rester.
