### ISSUE TITLE
Gestion du crash du bot quand il n'a pas la permission

### ISSUE THREAD

**Issue by JedXDs** [Virtual-Royaume/Royaume-Discord-Bot#107]
Le bot crash quand il n'a pas la permission tel que le système de création de channel ROYAUME DEV

**Comment by Bluzzi** [comment]
C'est un bug plutôt urgent mais je passe ça pour la V2.5 quand même vu que ça sera principalement du refactor et on va voir pour corriger toutes les erreurs de ce genre.

Si il y a d'autres erreurs comme celle-ci (en rapport avec le mode dev) n'hésitez pas à les poster ici @Virtual-Royaume/royaume-dev

**Comment by Steellgold** [comment]
Vu que je suis en vacances je vais le faire @Bluzzi

**Comment by Onirez** [comment]
Et c’est une raison pour m’envoyer un mail ?
