### ISSUE TITLE
Amélioration des textes de la commande `/member`

### ISSUE THREAD

**Issue by Bluzzi** [Virtual-Royaume/Royaume-Discord-Bot#111]
Sachant que l'on écrit maintenant le temps en jour, heure et minute.
![image](https://user-images.githubusercontent.com/20624478/195244665-edd8451e-0031-4c54-bd95-880d50081687.jpeg)

**Comment by JedXDs** [comment]
Jai déjà réglé ça dans mon dernier commit normalement

**Comment by Bluzzi** [comment]
Dans le même style il y a une petite étoile en trop sur la ligne d'anniversaire. @JedXDs 
![image](https://user-images.githubusercontent.com/20624478/195321251-792bc6ea-c33d-421c-9dcb-275e123ed6bb.png)
