### ISSUE TITLE
Réactions aux liens

### ISSUE THREAD

**Issue by Verre2OuiSki** [Virtual-Royaume/Royaume-Discord-Bot#113]
Actuellement, le système de réaction aux liens ne fonctionne plus *(github link, discord message link)*.

**Comment by Bluzzi** [comment]
J'ai vérifié sur le portail de développeur Discord, le contenu des messages est activé. C'est donc soit un intent de message pas mis soit une autre erreur dans le code.

**Comment by Bluzzi** [comment]
Tu as debug un peu cette issue ? @Verre2OuiSki 

Est-ce qu'on a encore accès au contenu des messages ou le bug vient de plus loin ?
