### ISSUE TITLE
Message de bienvenue

### ISSUE THREAD

**Issue by Verre2OuiSki** [Virtual-Royaume/Royaume-Discord-Bot#125]
Actuellement, a chaque nouveau membre sur le serveur un long message identique a chaque fois est envoyé.
Je trouve que ca "pollue" le salon.
Je pense qu'il serait plus judicieux d'envoyer un petit message de bienvenue comme `Bienvenue parmi nous @user !` pour toujours être notifié d'un nouveau membre, et lui envoyer le long message en MP ou en ephemeral si ses messages privés sont bloqués

**Comment by Steellgold** [comment]
Je suis du même avis

**Comment by Bluzzi** [comment]
Hello, je pense qu'on a tous remarqué ce probleme, je pense que c'est même quelque chose qui pourrait passer en prod directement car ça me semble très important ! (PR depuis main/vers main quand même, je m'occuperais de le merge sur la prod de mon côté)

J'ai un gros doute sur le fait qu'on puisse send un message en "ephemeral" hors d'une "interaction" mais si c'est possible il faudra faire ça dans l'optimal oui. Sinon, si MP ouvert alors en MP, si pas ouvert alors dans le `#discussion` quand même.
