### ISSUE TITLE
Suppression de la commande `/watch-together`

### ISSUE THREAD

**Issue by Bluzzi** [Virtual-Royaume/Royaume-Discord-Bot#128]
Cette fonctionnalité est maintenant disponible directement sur Discord par défaut, elle doit donc être supprimé.

**Comment by EmptySckills** [comment]
Mais cela est une fonctionnalité Nitro non ?

**Comment by Bluzzi** [comment]
@EmptySckills quand tu es connecté à un vocal sans Nitro, tu n'as pas accès à ça ?

![image](https://user-images.githubusercontent.com/20624478/198353570-5987a4dc-9fcd-4821-a4bc-ba723a41c7eb.png)

A savoir que je viens de déplacer cette fonctionnalité dans le milestone V2.6.0 donc ça n'arrivera pas avant plusieurs mois encore.

**Comment by EmptySckills** [comment]
Je n'ai pas discord ahah je suis un old skype user, mais il me semble que certaines activitées sont nitro je croyais que Youtube en faisait parti

**Comment by JedXDs** [comment]
Il y a des activités disponible gratuitement et certains avec Nitro.

**Comment by Steellgold** [comment]
> Il y a des activités disponible gratuitement et certains avec Nitro.

Oui mais la commande `/watch-together` n'est plus d'utilité justement, Youtube Together est gratuit
![image](https://user-images.githubusercontent.com/51505384/199224886-dc80a831-ef5c-4586-9990-9f83b8119e8c.png)
