### ISSUE TITLE
Proposition de fonctionnalitée pour le divertissement

### ISSUE THREAD

**Issue by Steellgold** [Virtual-Royaume/Royaume-Discord-Bot#129]
Dans une configurations du bot il y aurait un fichier JSON avec une liste de mots (le + possible)

Et plusieurs fois dans la journée (aléatoirement) le bot envoi dans le salon général un de ces mots mais écrit dans le désordre.

Celui qui le réecrit en premier gagne par exemple des points d'activitée (ou pas)

Exemple: 
```JSON
{
  "words": [
	"Bouton de cuivre",
	"Symphonia",
	"Minecraft",
	"League of Legends"
  ]
}
```
![image](https://user-images.githubusercontent.com/51505384/198336592-acb5b79f-f6d1-4ff4-8e08-846d89eff738.png)

**Comment by Bluzzi** [comment]
Dans le prochain milestone pourquoi pas, mais ça ne doit pas affecter le système d'activiter car il doit pousser un maximum à l'activiter classique et pro, pas celle de mini-jeux, c'est pas l'idée qu'on veux.

**Comment by Steellgold** [comment]
👌

**Comment by Verre2OuiSki** [comment]
Ca sereait cool d'avoir aussi un jeu similaire a celui-la mais avec du code.
On aurait par exemple :
```js
let a = 10;
let b = 5;
let result = 0;

do {
  result++;
  a--;
} while (a > b);

result += a;

// Donner la valeur de `result`
```
Et la réponse serait `10`

Bien évidement la triche est facile, mais aucun intérêt de le faire. Tu n'apprends rien et tu ne gagne rien...

**Comment by Bluzzi** [comment]
Après réflexion, je ne pense pas que ce soit une bonne idée, ça demanderait du travail pour maintenir des nouvelles questions et au final l'activité généré semblé forcé.
