### ISSUE TITLE
Amélioration de la commande `/inactive`

### ISSUE THREAD

**Issue by Bluzzi** [Virtual-Royaume/Royaume-Discord-Bot#134]
# Problème 
Le Discord accueil beaucoup de nouveau membre en ce moment et donc le trie des membres inactifs devient plus long et difficile, la commande `/inactive` n'est plus assez optimisé pour gérer ça.

# Solution
Il faudrait totalement changer son fonctionnement, quand on exécute la commande, elle devrait afficher un embed qui affiche un seul membre inactif avec des statistiques pertinentes :
- pseudo
- tag Discord (mention)
- nombre de message total 
- temps de vocal total
- date du dernier message 
- tier d'activité 

Cette embed aurait trois boutons :
- précédent : voir l'inactif précédent 
- kick : exclure cette inactif
- suivant : voir l'inactif suivant 

Cela permettrait de pouvoir trier les membres sans devoir faire d'autres commandes ou manipulations.

**Comment by Steellgold** [comment]
> kick : exclure cette inactif

Pour tout les membres, ou seulement ceux qui ont la permission ?

**Comment by Bluzzi** [comment]
Uniquement ceux qui ont la permission, de toute façon la commande est déjà sensé être soumise à ceux qui ont la permission. Mais oui il faut vérifier si le membre à la permission de kick pour exécuter la commande et pour utiliser le bouton de kick (sécurité).

**Comment by Steellgold** [comment]
![image](https://user-images.githubusercontent.com/51505384/210179011-4c45d622-8996-469c-bbdb-c6a00aa9a664.png)
![Uploading image.png…]()
