### ISSUE TITLE
Commande `/forum how` pour savoir poser une question

### ISSUE THREAD

**Issue by Unarray** [Virtual-Royaume/Royaume-Discord-Bot#154]
Je vois beaucoup de gens créer des post dans les salons forums sans donner d'explications, d'entrée/sortie attendu ou tout autre. On a aucun contexte et ce manque de données mene a confusion *(@Bluzzi et moi même en avons fait les frais)*

Il faudrait donc faire cette commande *(le nom peut être changé)* pour montrer au gens comment poser un problème pour avoir des réponses de qualités

Pour la rédaction du message, inspirez-vous de [ce post twitter](https://twitter.com/melvynxdev/status/1538552526445850625?s=20&t=jv7m9rH-AdSJcKFm7NBGzg2)

**Comment by Bluzzi** [comment]
Hello, du coup on fait ça directement dans le "Guide des posts", ou on ajoute quand même une commande ?
