### ISSUE TITLE
le message de présention ne se update pas 

### ISSUE THREAD

**Issue by royaljacques** [Virtual-Royaume/Royaume-Discord-Bot#156]
hello, suite à un test, j'ai remarqué que le message de présentation ne s'update pas.
il serais cool que si qq loupe sa présentation ou bien veux modifier sont message d'origine, le message de présentation soit update directement . avec un petit compteur de modifications .

**Comment by Bluzzi** [comment]
J'aime bien la suggestion, c'est pertinent
