### ISSUE TITLE
Alternative à `Colors`

### ISSUE THREAD

**Issue by Steellgold** [Virtual-Royaume/Royaume-Discord-Bot#174]
Pourquoi ne pas utiliser [`Chalk`](https://www.npmjs.com/package/chalk) ? Au lieu de colors qui n'a pas eu de nouvelles versions depuis 3 ans et qui n'a pas de déclarations TS par rapport à Chalk.

![image](https://user-images.githubusercontent.com/51505384/219954224-2f536f2e-3410-4aeb-9358-53a76e530429.png)
![image](https://user-images.githubusercontent.com/51505384/219954282-181ebed9-2368-4f0c-a588-03b17fce723c.png)

**Comment by Bluzzi** [comment]
On a déjà utilisé `chalk` et `colors` :
- `chalk` : de souvenir il a un problème avec les ES module donc on ne peut pas utiliser la dernière version
- `colors` : plus maintenu, il a eu une mauvaise réputation suite au code malveillant du mainteneur principal 

Le système qu'on utilise actuellement est simple, efficace, ne require pas de lib externe. C'est aussi bien.
