### ISSUE TITLE
Changer l'affichage du /member 

### ISSUE THREAD

**Issue by royaljacques** [Virtual-Royaume/Royaume-Discord-Bot#183]
### Description de l'issue

Actuellement le /member est un embed . je souhaite pouvoir le modifier afin de pouvoir faire nous même un affiche plus moderne du discord .

l'ajout d'image pourrais donner un peux de sympatie et ne pas rester tous les couleurs de discord .

### Quelle solution proposez-vous ?

passer par canvas afin de customiser une image 

### Avantages et inconvénients

Meilleur affichage 
meilleur gestion du contenus 
permettre de rajouter plus de choses par la suite en agrandissant potentiellement l'image

**Comment by Steellgold** [comment]
@royaljacques Des news ?

**Comment by royaljacques** [comment]
ah non mince il faut que j'y retourne la car il faut je m'entraine sur canvas
