### ISSUE TITLE
Multiples activitées

### ISSUE THREAD

**Issue by Max13-js** [Virtual-Royaume/Royaume-Discord-Bot#186]
### Description de l'issue

Pour que le bot affiche les activités sur le discord game faudrait faire des shards. Vous pouvez ainsi séparer les shards et en avoir 1 sur le game et 1 sur le "pro".

https://discordjs.guide/sharding/#how-does-sharding-work

**Comment by Unarray** [comment]
Je viens de voir ce que sont les shards et je trouve ca overkill d'utiliser ce système pour juste avoir une activité différente sur deux serveurs discord

**Comment by Max13-js** [comment]
Ta geule on s'en fou le bot prends pas bcp de perf bluzzi s'en fou il a dit et puis les activités c'est giga fun donc faut faire ca
