### ISSUE TITLE
Mauvaise conception du test

### ISSUE THREAD

**Issue by Unarray** [Virtual-Royaume/Royaume-Discord-Bot#209]
En me baladant sur le code, j'ai remarqué que [cette fonction](https://github.com/Virtual-Royaume/Royaume-Discord-Bot/blob/ee04766866e0fcb8dd08d2c1c305098d93d5bc91/src/utils/validator/color.util.ts#L3) avait été mal conçue.
En effet, si on observe attentivement la regex, on peut observé qu'elle test la chaine de charactères sans prendre en compte que les lettres sont comprise uniquement entre `A` et `F` *(dans la regex actuelle elle regard uniquement si c'est une lettre, donc de `A` à `Z` ce qui est faut dans notre test)*

Donc il faudrait modifier le test pour réellement tester si c'est une valeur hexadécimale ou non.

**Comment by Bluzzi** [comment]
Oh je ne savais pas, les codes hex ne prennent que les lettres entre A et F c’est ça ?

**Comment by Steellgold** [comment]
> Oh je ne savais pas, les codes hex ne prennent que les lettres entre A et F c’est ça ?

Le code hex fonctionne en utilisant une base de numérotation hexadécimale (base 16), où chaque chiffre peut représenter une valeur de 0 à 15. Les chiffres hexadécimaux vont de 0 à 9, puis de A à F. Le code hex est souvent utilisé pour représenter les couleurs dans les applications web et les systèmes informatiques. Chaque couleur est représentée par une combinaison de six chiffres hexadécimaux, où les deux premiers chiffres représentent la quantité de rouge, les deux chiffres suivants représentent la quantité de vert, et les deux derniers chiffres représentent la quantité de bleu.
- Bottly
