### ISSUE TITLE
Système de musique 

### ISSUE THREAD

**Issue by Bluzzi** [Virtual-Royaume/Royaume-Discord-Bot#52]
Création d'un systeme pour pouvoir écouter de la musique sur le bot à travers différentes commandes.

### Commandes
- `play (lien youtube ou spotify)` : 
    1. le bot rejoint le salon vocal de la personne qui a effectué la commande (sauf si il est déjà dedans)
    2. le bot effectue une action selon 
        - si aucune musique n'est en cours de lecture, il lance la musique demandé 
        - si une musique est en lecture il ajoute la musique demandé à la queue
        - si la musique est en pause, il relance la musique
- `stop` : met en pause la musique 
- `clear` : stop/supprime la musique en lecture et supprime toutes les musiques dans la queue
- `skip` : passe à la musique suivante de la queue si il y en a une 
- `lyrics` : envoie les paroles de la musique en cours de lecture 

### Liens utiles 
- [DiscordJS/Voice](https://discordjs.guide/voice/)
- [Spotify API](https://rapidapi.com/Glavier/api/spotify23/?utm_source=twitter.com%2FRapid_API&utm_medium=DevRel&utm_campaign=DevRel)
- [Genius Lyrics API](https://rapidapi.com/Glavier/api/genius-song-lyrics1/?utm_source=twitter.com%2FRapid_API&utm_medium=DevRel&utm_campaign=DevRel)

**Comment by Steellgold** [comment]
@Bluzzi Je crois que tu t'es trompé ? "Shopify API" ce n'est pas plutôt "Spotify API" 😅
