### ISSUE TITLE
Tier d'activité sur la commande ``/member``

### ISSUE THREAD

**Issue by Bluzzi** [Virtual-Royaume/Royaume-Discord-Bot#63]
Afficher le tier d'activité dans la commande ``/member`` ainsi qu'une indication pour savoir si on est plus proche de monter ou descendre d'un rank à la fin du mois.

Cette issue dépend de cette release : https://github.com/Virtual-Royaume/Royaume-API/releases/tag/3.3.0

**Comment by Verre2OuiSki** [comment]
En attente d'update coté API
