### ISSUE TITLE
Erreur de créations des salons

### ISSUE THREAD

**Issue by Steellgold** [Virtual-Royaume/Royaume-Discord-Bot#79]
Lorsqu'on lance le bot, il arrive qu'il créé les salons vocaux par défaut (dans la task `ChannelManager`) alors qu'ils existent déjà. 

![image](https://user-images.githubusercontent.com/51505384/178054251-dbf3d19b-8a85-44c7-b5c0-94cc7a1b582e.png)

**Comment by Bluzzi** [comment]
Cette PR n'a pas pu être reproduite, si une reproduction est possible il faudra la réouvrir avec une explication pour reproduire ce bug.

**Comment by Steellgold** [comment]
> Cette PR n'a pas pu être reproduite, si une reproduction est possible il faudra la réouvrir avec une explication pour reproduire ce bug. 

C'était lors ce que le bot (dev) s'allume et de connecté que tout les salons se créeait
