### ISSUE TITLE
Idée: Non-flood

### ISSUE THREAD

**Issue by Steellgold** [Virtual-Royaume/Royaume-Discord-Bot#81]
Ajouter un bouton "❌" ou "Supprimer" sous les messages, exemple `/top-voice` ou dans le même genre.
Pour une fois cliqué le message se supprime (pour les messages non éphèmeres)

**Comment by Bluzzi** [comment]
Perso je suis vraiment pas fan, le salon commande suffit pour l'instant et j'apprécie qu'on spam dedans, j'aime bien voir qui fait qu'elle commande. De base je voulais laisser toutes les commandes visible

**Comment by Steellgold** [comment]
D'accord, aucun problème sur cela, à voir si d'autres avis se rajoutent, je fermerai si d'ici 4-5 jours pas d'autres avis
