### ISSUE TITLE
Configuration pour le stockage des messages

### ISSUE THREAD

**Issue by Bluzzi** [Virtual-Royaume/Royaume-Discord-Bot#82]
Les messages sont actuellement tous directement dans le code, ça serait bien d'avoir une config ou l'on stock tout les messages avec un systeme permettant de les utilisés en replaçant des tags par des params.

**Comment by Steellgold** [comment]
On pourait plutôt faire directement dans un fichier (.lang)

Si par exemple il y a un fichier fr_FR, us_US sa va proposer ces deux, directement pour le serveur via pourquoi pas `/serverlang [Fichiers proposées]` 

C'est qu'une idée.

**Comment by Bluzzi** [comment]
Pour l'instant je ne parle pas forcement de lang mais simplement de stockage des messages. Pourquoi utiliser un ``.lang`` quand des fichiers comme ``JSON`` sont supporté par default par le JS ?

**Comment by Steellgold** [comment]
Oui, aussi
