### ISSUE TITLE
Mettre en avant la sélection des rôles 

### ISSUE THREAD

**Issue by Bluzzi** [Virtual-Royaume/Royaume-Discord-Bot#87]
Actuellement, beaucoup de membres n'ont aucun rôle sélectionné. Sûrement car ils n'ont pas conscience de cette possibilité. 

Dans le cas ou un membre a aucun rôle, il faudrait leur envoyer un rappel en MP (ou dans le salon principal si ils sont fermé) pour leur dire de choisir leur rôles via la commande `/role`.

**Comment by JedXDs** [comment]
A quelle fréquence tu voudrais les faire rappeler ? Un bouton sur le message de bienvenue serait t-il pas une bonne idée à envisager ?

**Comment by Bluzzi** [comment]
> A quelle fréquence tu voudrais les faire rappeler ? Un bouton sur le message de bienvenue serait t-il pas une bonne idée à envisager ?

Une fois par mois, avec une task qui check tout simplement si le membre a un rôle ou non (en dehors des rôles de tier).

**Comment by Bluzzi** [comment]
> Faire au moment de la présentaiton le choix de roles ?

Nop il faudrait vraiment un rappel tout les X temps, il y a déjà une demande lorsque les membres rejoignent mais ils ne prennent pas toujours leurs rôles.

**Comment by Steellgold** [comment]
> > A quelle fréquence tu voudrais les faire rappeler ? Un bouton sur le message de bienvenue serait t-il pas une bonne idée à envisager ?
> 
> Une fois par mois, avec une task qui check tout simplement si le membre a un rôle ou non (en dehors des rôles de tier).

Cependant les tasks ne dureront jamais un mois ?
Plutôt rappeller comme par exemple les changements de rôles donc, le 1 ou milieu de mois

Si possible d'envoyer un DM alors on le fait sinon on mentionne les personnes dans un message en leur disant

Mais les membres qu'on mentionnerai doivent avoir aucun des roles (possible de sélection) si il a au moins 1 rôle alors il n'est pas compté

**Comment by Bluzzi** [comment]
Tu as bien résumé :
- le rappel ne doit concerner que ceux qui ont aucun rôle de sélectionné 
- une task qui tourne et qui va envoyer un rappel tout les 3 de chaque mois 
    - soit rappel en DM si possible (attention au rate limit) 
    - soit un rappel global dans le salon `#discussion` qui mentionne toutes les personnes concernés

**Comment by Steellgold** [comment]
Donc prendre la base du message de bienvenue pour envoyer ou pas en DM, et prendre la base du message mensuel pour les passage de rôles?

**Comment by Steellgold** [comment]
@JedXDs Tu t'en occupe? Sinon je peut le faire dès que j'ai finis ce que je suis entrain de faire

**Comment by Bluzzi** [comment]
@Unarray, je pense que cette issue à encore besoin d'un peu de réflexion du aux récents changement d'organisation du Discord.

Pour l'instant laisse cette issue de côté dans ta PR, on reviendra dessus après ce gros refactor !
