### ISSUE TITLE
Ajout du support des salons forums 

### ISSUE THREAD

**Issue by Bluzzi** [Virtual-Royaume/Royaume-Discord-Bot#88]
Les salons forums ne sont pas supporter pour l'ajout de stats sur les messages. Il faut que ça soit le cas rapidement.

**Comment by Verre2OuiSki** [comment]
Pour le moment, `[discord.js](https://github.com/discordjs/discord.js)` ne prend pas en charge les salons forum dans les `SlashCommand`
Je pense que cette fonctionnalité sera pris en charge dans la prochaine version du package *(v14.6.0)* car un commit a été fait sur leur projet
